export const SET_NOTIFICATION = 'SET_NOTIFICATION';
export const SET_NOTIFICATION_TYPE = 'SET_NOTIFICATION_TYPE';
export const SET_SELECTED_OPTION = 'SET_SELECTED_OPTION';
export const SET_EMAIL_VALUE = 'SET_EMAIL_VALUE';
